### PR TITLE
Update to 1.19.4. Maybe?

### PR DESCRIPTION
**Pull request by JaaiDead**

### CODE REVIEW

**Comment by comp500** [comment]
MixinTrace already works on 1.19.4...?

**Comment by JaaiDead** [comment]
yup just updated the files to 1.19.4

**Comment by comp500** [comment]
It doesn't need updating, there are no functional changes made by this PR. The version from 1.17 works fine on 1.19.4, there isn't any reason to release a new version.

**Comment by JaaiDead** [comment]
ok

**Pull request closed without merging**
