### PR TITLE
Fix of #5

### LINKED ISSUE #5: Broken on Fabric Loader 0.12.0+ (and 1.18+)
A crash on loader 0.12.1: https://hastebin.com/isixedepes.yaml
Same crash on loader 0.11.7: https://hastebin.com/axomarowit.yaml

See https://fabricmc.net/2021/10/03/loader-0120.html#mixin-compatibility for more info on what exactly changed in loader in regards to 0.12.

### PR DESCRIPTION
**Pull request by MagicSweet-dev**
This pull request also fixes #5

### CODE REVIEW

**Comment by comp500** [comment]
Have you tested that this works? I have an unmerged PR to Mixin which specifically fixes the getAppliedMixins function.

**Comment by MagicSweet-dev** [comment]
I _have_ actually done some testing now and the latest commit to my repo mod is working.
[This mod](https://github.com/comp500/mixintrace/files/7796983/fabric-example-mod.zip) ([jar binary](https://cdn.discordapp.com/attachments/776794602145054773/926568346651074650/fabric-example-mod-1.0.0.jar)) was quickly made and used for testing - it throws an IllegalStateException on F3+F4 by modifying `Keyboard`'s `processF3(int)` method  with `@Inject`

[Crash Report](https://pastebin.com/NVfELwVi)
[Logs](https://github.com/comp500/mixintrace/files/7796995/latest.log)
[MixinTrace Jar](https://cdn.discordapp.com/attachments/776794602145054773/926569936220999690/mixintrace-1.1.11.18.1.jar) _(in case if you're too lazy to compile it yourself)_

**Comment by MagicSweet-dev** [comment]
Also a [crash report](https://pastebin.com/7RHxngG1) within my daily modpack (basically real environment), including the test mod _(if you need such data ofc)_
Mod list is provided with a crash report

**Comment by srnyx** [comment]
How can I build this? When I run `gradlew build` I get this error: https://paste.srnyx.xyz/axafuguvav.apache (and the build fails)

**Comment by MagicSweet-dev** [comment]
> How can I build this? When I run `gradlew build` I get this error: https://paste.srnyx.xyz/axafuguvav.apache (and the build fails)

You should install Java 17 and run your build with it. Minecraft requires Java 17 since 1.18

**Comment by srnyx** [comment]
> > How can I build this? When I run `gradlew build` I get this error: [paste.srnyx.xyz/axafuguvav.apache](https://paste.srnyx.xyz/axafuguvav.apache) (and the build fails)
> 
> You should install Java 17 and run your build with it. Minecraft requires Java 17 since 1.18

https://github.com/MagicSweet-dev/mixintrace/blob/master/build.gradle#L6-L7

**Comment by MagicSweet-dev** [comment]
Seems like *the Gradle wrapper itself* were incompatible with Java 17 🤪

**Comment by comp500** [comment]
Hmm... could you change the PR to just fix #5 and not port to a newer Minecraft version? It'd be great to keep compatibility between Minecraft versions with just one jar if it works, since this is only dependent on the Fabric loader version.

**Comment by MagicSweet-dev** [comment]
Test environment crash reports:
[1.17](https://github.com/comp500/mixintrace/files/8881319/crash-2022-06-10_21.37.01-client.txt) (native project version)
[1.18.1](https://github.com/comp500/mixintrace/files/8881668/crash-2022-06-10_21.58.10-client.txt) (25 mods total, real environment)
[1.19](https://github.com/comp500/mixintrace/files/8881597/crash-2022-06-10_21.51.59-client.txt)

Mod used in these environments could be found above ([here](https://github.com/comp500/mixintrace/pull/7#issuecomment-1003446311))

You probably also want to bump the mixintrace's version after merging

**Comment by comp500** [comment]
Thanks!

**Comment by srnyx** [comment]
So with this merged, MixinTrace now supports 1.17+?

**Comment by comp500** [comment]
MixinTrace always supported 1.17+, the incompatibility is with Fabric loader versions...

**Pull request merged**
